[BE] 회원 가입 기능 구현
codesuqad-team3-to-do-list/todo-max pull request #55
Opened 2023-07-19 10:36 UTC by crtEvent

## What is this PR? 👓
- 회원 가입 기능을 구현했습니다.

## Key changes 🔑
- URI: `POST` `/api/signin`
- email, password를 받아서 회원 가입 합니다.
- email로 이미 가입한 email인지 검증한 뒤 회원 가입 합니다.
- email이 중복일 경우 회원 가입에 실패하며 400 BAD REQUEST를 반환합니다.
- 회원 가입 성공일 경우 201 Created를 반환합니다.

## To reviewers 👋
- 아직 JWT 인증 쪽 리팩토링이 되지 않아 URI, 패키지 구조, class 명 등 수정해야 할 부분이 있는지 확인해 봐야 할 듯.

2023-07-19 11:20 UTC, jinny-l requested changes
수고하셨습니다!
코멘트 한번 확인 부탁드릴게용

2023-07-19 11:20 UTC, jinny-l commented on BE/app/src/main/java/com/todo/app/common/exception/MemberDuplicationException.java
> +
400 에러를 선택하신 이유가 있을까욤?

2023-07-19 11:20 UTC, jinny-l commented on BE/app/src/main/java/com/todo/app/domain/jwt/controller/request/SignInRequest.java
> +
활동기록에서 프로필 이미지랑 닉네임이 보여지는 상황인데,
시간관계상 이미지는 패스한다해도 프론트랑 닉네임 관련된 협의는 해야 할 것 같네용

2023-07-19 11:20 UTC, jinny-l commented on BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepository.java
> +    void saveMember(String email, String password);
`void save(Member member);` 이런식으로 해도 될 것 같긴한데
email이랑 password를 따로 받는 이유가 있을까용?

2023-07-19 11:20 UTC, jinny-l commented on BE/app/src/main/java/com/todo/app/domain/jwt/service/JwtService.java
> +
sign in은 로그인이고 sign up이 회원가입인 것 같은뎀
수정이 필요할 것 같네욤 🥲

2023-07-19 11:23 UTC, crtEvent commented on BE/app/src/main/java/com/todo/app/common/exception/MemberDuplicationException.java
> +
중복된 이메일을 입력한 것이 사용자의 잘못된 요청이라고 생각했어요.

400 Bad Request가 '클라이언트 오류(예: 잘못된 요청 구문 ...)를 감지해 요청을 처리할 수 없거나, 하지 않는다는 것을 의미'한다고 나와 있어서 400이 적합하다고 생각했습니다.
[400 Bad Request](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/400)

2023-07-19 11:25 UTC, crtEvent commented on BE/app/src/main/java/com/todo/app/domain/jwt/controller/request/SignInRequest.java
> +
넵! 프론트쪽 회원 가입 페이지에 닉네입 입력란이 없길래 일단 제외했습니다.

상의 후 추가해야겠네요.

2023-07-19 11:33 UTC, crtEvent commented on BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepository.java
> +    void saveMember(String email, String password);
## save() 메서드 명
- save라는 이름은 Repository랑 패키지가 jwt로 되어 있어서 save가 Member를 뜻하는지 Jwt를 뜻하는지 모호해서 saveMember로 명시했습니다.

- findBy 같은 경우는 반환 타입에 Member가 있어서 무엇을 찾아오는지 알 수 있는데 save는반환타입이 없어서 명시해줘야된다고 생각했어요.

## Parameter
- 단순히 필요한 값만 받고 싶었습니다.
- Member를 쓰면 파라미터 순서를 헷갈릴 일이 없어서 좋을 것 같네요.
- 이렇게 할까 고민했었는데 사실 Member가 무슨 역할인지 모르겠습니다. id가 빈 값인 상태의 Member 객체로 변환하는 건 그냥 Request Dto 쓰는 거랑 다를 바 없는 것 같아요.

2023-07-19 11:33 UTC, crtEvent commented on BE/app/src/main/java/com/todo/app/domain/jwt/service/JwtService.java
> +
수정하겠습니다. 정신 차리고 할게요. 🥲🥲🥲

2023-07-19 14:11 UTC, merged

2023-07-20 08:12 UTC, jinny-l commented on BE/app/src/main/java/com/todo/app/domain/jwt/controller/request/SignInRequest.java
> +
프론트쪽이랑 이메일 @ 왼쪽을 닉네임 영역으로 표시하기로 햇습니다.